// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl0pvPUR_bVLQQjYp9iQ8T12kWnwk_r-g',
    appId: '1:920148270574:web:703c8d62130437086f82ff',
    messagingSenderId: '920148270574',
    projectId: 'agriiot-7798a',
    authDomain: 'agriiot-7798a.firebaseapp.com',
    storageBucket: 'agriiot-7798a.firebasestorage.app',
    measurementId: 'G-Y99GT2TFQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Sut-evwGeMEzPyLj42Y16_pyed3KZgI',
    appId: '1:920148270574:android:de216bc9deeaee4e6f82ff',
    messagingSenderId: '920148270574',
    projectId: 'agriiot-7798a',
    storageBucket: 'agriiot-7798a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbVfu4uU4oAElEN8BOQ2gMOxWN68Clmc',
    appId: '1:920148270574:ios:2c5998ab52f1f8516f82ff',
    messagingSenderId: '920148270574',
    projectId: 'agriiot-7798a',
    storageBucket: 'agriiot-7798a.firebasestorage.app',
    iosBundleId: 'com.example.agriculture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbVfu4uU4oAElEN8BOQ2gMOxWN68Clmc',
    appId: '1:920148270574:ios:2c5998ab52f1f8516f82ff',
    messagingSenderId: '920148270574',
    projectId: 'agriiot-7798a',
    storageBucket: 'agriiot-7798a.firebasestorage.app',
    iosBundleId: 'com.example.agriculture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl0pvPUR_bVLQQjYp9iQ8T12kWnwk_r-g',
    appId: '1:920148270574:web:a32e7a1c3b89da306f82ff',
    messagingSenderId: '920148270574',
    projectId: 'agriiot-7798a',
    authDomain: 'agriiot-7798a.firebaseapp.com',
    storageBucket: 'agriiot-7798a.firebasestorage.app',
    measurementId: 'G-TDJ40GQJ99',
  );
}
