// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_apiKey']!,
    appId: dotenv.env['FIREBASE_WEB_appId']!,
    messagingSenderId: dotenv.env['FIREBASE_WEB_messagingSenderId']!,
    projectId: dotenv.env['FIREBASE_WEB_projectId']!,
    authDomain: dotenv.env['FIREBASE_WEB_authDomain']!,
    storageBucket: dotenv.env['FIREBASE_WEB_storageBucket']!,
    measurementId: dotenv.env['FIREBASE_WEB_measurementId']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_apiKey']!,
    appId: dotenv.env['FIREBASE_ANDROID_appId']!,
    messagingSenderId: dotenv.env['FIREBASE_ANDROID_messagingSenderId']!,
    projectId: dotenv.env['FIREBASE_ANDROID_projectId']!,
    storageBucket: dotenv.env['FIREBASE_ANDROID_storageBucket']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_apiKey']!,
    appId: dotenv.env['FIREBASE_IOS_appId']!,
    messagingSenderId: dotenv.env['FIREBASE_IOS_messagingSenderId']!,
    projectId: dotenv.env['FIREBASE_IOS_projectId']!,
    storageBucket: dotenv.env['FIREBASE_IOS_storageBucket']!,
    iosBundleId: dotenv.env['FIREBASE_IOS_iosBundleId']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_apiKey']!,
    appId: dotenv.env['FIREBASE_MACOS_appId']!,
    messagingSenderId: dotenv.env['FIREBASE_MACOS_messagingSenderId']!,
    projectId: dotenv.env['FIREBASE_MACOS_projectId']!,
    storageBucket: dotenv.env['FIREBASE_MACOS_storageBucket']!,
    iosBundleId: dotenv.env['FIREBASE_MACOS_iosBundleId']!,
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_apiKey']!,
    appId: dotenv.env['FIREBASE_WINDOWS_appId']!,
    messagingSenderId: dotenv.env['FIREBASE_WINDOWS_messagingSenderId']!,
    projectId: dotenv.env['FIREBASE_WINDOWS_projectId']!,
    authDomain: dotenv.env['FIREBASE_WINDOWS_authDomain']!,
    storageBucket: dotenv.env['FIREBASE_WINDOWS_storageBucket']!,
    measurementId: dotenv.env['FIREBASE_WINDOWS_measurementId']!,
  );
}
